### ISSUE TITLE
blocks being rejected x11 algo

### ISSUE THREAD

**Issue by goodthebest** [pallas1/joincoin#2]
Dev, I'm using POS as rpcencoding and blocks are being rejected using yiimp software. Is there any dev fees etc to be paid or stratum side modification needed to make it compatible with joincoin?

**Comment by pallas1** [comment]
no modifications needed, you just need to configure the wallet to use the correct algo (one per wallet instance).

**Comment by goodthebest** [comment]
I'm using headless linux wallet and configuration is this, but blocks are being rejected, rcpencoding I'm using is POS and software is yiimp. How to fix block rejection?

![image](https://user-images.githubusercontent.com/1715740/51049278-d7e0b500-15e6-11e9-908e-e5a7f4b18b55.png)
